### ISSUE TITLE
Export of recalibrated routes should truncate an existing route table in postgres instead of drop

### ISSUE THREAD

**Issue by hdus** [blazek/lrs#13]
When an existing routing table is exported to postgres, it will be dropped. In case of depending views dropping of the route table is not possible. Truncation instead of dropping the table would be much better.

**Comment by blazek** [comment]
I am currently upgrading the plugin to QGIS3 and refactoring it to use measure support in QGIS. My intention is to remove the export tab in favour of QGIS standard export possibilities, which I am testing just now. In the new version, the output from calibration is a memory layer which can be saved as shapefile with "Save as" or (not yet got it working) dragged and dropped to postgis in browser or imported in dbmanager.

It won't probably resolve your problem without other changes in QGIS export/import tools, which, OTOH, may be useful in general? I mean drag and drop in the browser should/could offer dialog with delete/truncate options if the table already exists?

In the old version for QGIS2, it won't be probably fixed.

**Comment by blazek** [comment]
I have uploaded the version upgraded for QGIS 3 where the layer with measures is created as memory layer, which can then be exported using standard QGIS tools. So this issue becomes irrelevant and the problem should be fixed in QGIS core.
