### ISSUE TITLE
events grayed out in 0.3.7

### ISSUE THREAD

**Issue by inedecubber** [blazek/lrs#22]
Hi,
I wanted to experiment with this LRS plugin. 
I'm running Qgis 2.18.16, and I installed LRS plugin 0.3.7.
when I run the plugin, everything is grayed out, except the fields in the "calibration" tab.
I can click in the "events" tab, but I can't select an event layer, route field or whatever.

![lrs plugin callibration tab](https://user-images.githubusercontent.com/22191769/40927974-73afac2c-6820-11e8-9719-76b579f91337.png)
![lrs plugin events tab](https://user-images.githubusercontent.com/22191769/40928020-95dee40c-6820-11e8-8311-ea166af449a0.png)

I have no idea what's wrong :(

**Comment by blazek** [comment]
Nothing is wrong, that is correct, calibration must be run first in 0.x on QGIS 2.x. 

In the new version 1.x on QGIS 3.x, the plugin is using as input for locate/events/measures a layer with measures (which may be saved as output of calibration).

**Comment by blazek** [comment]
> how can I run the callibration, if I don't have a point layer, in v 2.x?

You cannot.

> am I correct, that in v 2.x, I can't start immediately with the events?

Correct.
