### ISSUE TITLE
error returned if you calibrate in different CRS

### ISSUE THREAD

**Issue by gubuntu** [blazek/lrs#25]
If the project is in a different CRS to the LRS layer, calibrating fails

v1.02 in QGIS 3.2

**Comment by blazek** [comment]
Different projections should be handled, it should work so that it takes project's CRS if projection is enabled, otherwise line layer's CRS. 

Can you prepare small project + data where it fails? It is enough to ha single line, 2 points and project file. I cannot promis to fix it soon.

**Comment by blazek** [comment]
It should wok, if it does not, please reopen and if possible, create an example data set as described above.
