### ISSUE TITLE
Can't generate events from calculated measures: route not available

### ISSUE THREAD

**Issue by simonsouth** [blazek/lrs#36]
With certain datasets it is impossible to generate events from measures calculated via the "Measures" tab of the plugin: Although both operations appear to succeed, the resulting events layer contains no visible features, and each of its rows contains "route not available" in its error field.

The issue is the plugin's insistence on converting the source (LRS) layer's route field value to a string (at [lrsmeasures.py:95](https://github.com/blazek/lrs/blob/0bcf202b382e8e1af6281a8565598dee43b89f28/lrs/lrs/lrsmeasures.py#L95)) when writing it to the newly created measures layer. If the source layer's route field is of a non-string type, this can change the format of the value so it cannot be matched again later.

For example, in the dataset I'm working with, the route-identifier field is of type double. A route ID of "10000" in the source layer will be output as the string "10000.0" in the generated measures layer. When trying to generate events from this new layer, the route ID will no longer be matched in the source.

The straightforward solution appears to be preserving the type of the route field between the input and the output. Note [this is already done by the event-generation process](https://github.com/blazek/lrs/blob/0bcf202b382e8e1af6281a8565598dee43b89f28/lrs/lrs/lrsevents.py#L42-L44).

**Comment by blazek** [comment]
Fixed using Simon's pull request.
