### ISSUE TITLE
Join route ID field on Measurements tab

### ISSUE THREAD

**Issue by inakijimenez9** [blazek/lrs#42]
This is an enhancement proposal.
For points that already had the route id assigned to a field, it would be a good option to assign the measurement to the route defined on that field.

**Comment by simonsouth** [comment]
Turns out the project I'm working on could benefit from this feature as well. I've started implementing this and plan to have a pull request to review shortly.

**Comment by blazek** [comment]
Implemented by Simon South. Thank you Simon. 

Released in 1.1.0.
