### ISSUE TITLE
LRS calibration throws uncaught exception if project projection doesn't match data

### ISSUE THREAD

**Issue by mikebannis** [blazek/lrs#45]
Clicking 'OK' on the Calibration tab throws an uncaught TypeError if the project projection does not match the projection of the line and points layers. It would be fantastic if the plugin could detect this situation and let the user know all projections need to match, rather than throwing a rather cryptic exception. Stack trace is below. I would be interested in helping with this if needed.

2018-10-16T10:17:44     WARNING    Traceback (most recent call last):
              File "C:/Users/mike.bannister/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lrs\ui\lrsdockwidget.py", line 606, in generateLrs
              extrapolate=extrapolate, measureUnit=measureUnit)
              File "C:/Users/mike.bannister/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\lrs\lrs\lrscalib.py", line 132, in __init__
              self.lineTransform = QgsCoordinateTransform(lineLayer.crs(), self.crs)
             TypeError: QgsCoordinateTransform(): arguments did not match any overloaded call:
              overload 1: too many arguments
              overload 2: not enough arguments
              overload 3: not enough arguments
              overload 4: not enough arguments
              overload 5: argument 1 has unexpected type 'QgsCoordinateReferenceSystem'
Edited for grammar.

**Comment by simonsouth** [comment]
I've submitted a pull request that should fix this. The issue has to do with a change in the QGIS API in version 3 that has affected other areas of the plugin as well (see issues #28 and #34).

**Comment by blazek** [comment]
Merged, released 1.1.1 with the fix. Thank you Simon.
