### ISSUE TITLE
Possible Bug: LRS calibration/creation not using same CRS as source layers?

### ISSUE THREAD

**Issue by Saijin-Naib** [blazek/lrs#47]
I have a project where I am using EPSG:2264 for the project and the resultant layers, but generation of the LRS is done with EPSG:3857, placing my data in the Central African Republic. Setting the CRS of the generated LRS layer to EPSG:2264 will place it exactly where it belongs, indicating that the output CRS is just being assigned incorrectly.

Edit:
Checking the Errors layer will zoom to errors in the wrong location, ie. using the EPSG;3857 locations, not the correct EPSG:2264 locations after I have re-assigned the proper locations to the LRS layer. However, the highlighted box for points and lines are drawing in the correct EPSG:2264 locations.

**Comment by blazek** [comment]
I found a bug in error layers transformation, but that was simply failing with error message, not giving wrong results, strange. 

Fixed in version 1.1.2, please try with this new version. 

The output LRS layer CRS should be either project CRS if enabled or input line layer CRS.

**Comment by Saijin-Naib** [comment]
Seems to be fixed here. Quite happy!

**Comment by blazek** [comment]
I found another bug, if  LRS/project CRS was changed after an error layer was created, error features were not properly reprojected in next calibration. Fixed in 1.1.3.
