### ISSUE TITLE
Python/Qt-Bug progressBar.setValue

### ISSUE THREAD

**Issue by Ludwig-K** [blazek/lrs#55]
Hi, 
there are four Python-Bugs of the same type when using the Plugin under QGis 3.28.1-Firenze.
`TypeError: setValue(self, int): argument 1 has unexpected type 'float'`
Its allways the case where
`progressBar.setValue(percent)`
is called, workaround would be, to use 
`progressBar.setValue(int(percent))`
instead.
Files:
- lrsdockwidget.py, line 815
- lrsevents.py, line 135
- lrsmeasures.py, line 122
- lrsdockwidget.py, line 688

**Comment by blazek** [comment]
Do you know if the fix is backward compatible or setValue(percent) must be used with qgis < 3.28?

**Comment by Ludwig-K** [comment]
The Qt/PyQt-Version for QGis 3.28 is 5.15.3/5.15.6

According to documentation [QProgressbar.setValue](https://doc.qt.io/qt-5.15/qprogressbar.html#value-prop) officially accepts only int, in previous Qt-Versions too. The code-changes should therefore be backward compatible, but I can not test this. Obviously PyQt was not so type-strict in the past?

**Comment by blazek** [comment]
Published release 1.2.3 with the fix: https://plugins.qgis.org/plugins/lrs/version/1.2.3/
